In [169]:
import numpy as np 
import pandas as pd
from scipy.optimize import curve_fit
from scipy.optimize import minimize 
import matplotlib.pyplot as plt

In [200]:
def mequation(I,Thc,beta,n):
    """
    Analithic Function to relate the thickness of a film with its relative ratio of intensities, i.e I_r
    """
    return Thc*np.exp(-beta*I**(1.0/n))

In [201]:
def objective(x,df2):
    """
    El valor que retorne la función es el que se busca minimizar
    """
    thc=x[0]
    b=x[1]
    n=x[2]
    #print(e0)
    df2['Equation'] = mequation(df2.I_ratio,thc,b,n)
    df2['Discrepancy'] = (df2.index.get_level_values('Thickness')-df2.Equation)/df2.index.get_level_values('Thickness')*100
    dfaux=df2[df2.I_ratio!=0]
    return dfaux.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()#df2.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()

In [251]:
def orgdf(frame):
    """Change the format that comes from to excel as to manage the data"""
    energy=[]
    Iratio=[]
    thickness=[]
    for i in range(4):
        dic={}
        k=0
        for j in range(len(frame.loc[i])-1):
            energy.append(list(frame.loc[i])[0])
            Iratio.append(list(frame.loc[i])[k+1])
            thickness.append(list(frame.columns)[k+1])
            k+=1
    dic={'Energy':energy,'Thickness':thickness,'I_ratio':Iratio}
    df=pd.DataFrame(dic)
    return df

In [252]:
path='C:\\Users\\Juan Pablo Nicolás\\Documents\\FISICA\\FISICA ESTUDIO\\MICROSCOPIA ELECTRONICA\\paper ecuacion Ene2021\\Sim_batch\\Matrix Simulation\\EqvsDataexp.xlsx'

In [253]:
dfSi=pd.read_excel(path,'Si')
dfGlass=pd.read_excel(path,'Glass')
dfSS=pd.read_excel(path,'SS')

In [254]:
dffSi=orgdf(dfSi)
dffGlass=orgdf(dfGlass)
dffSS=orgdf(dfSS)

In [255]:
dffSi=dffSi.set_index(['Energy','Thickness']).sort_index()
dffGlass=dffGlass.set_index(['Energy','Thickness']).sort_index()
dffSS=dffSS.set_index(['Energy','Thickness']).sort_index()

Dejando libre todos los parámetros

In [264]:
l=[]
for e0 in [12,18,24,30]:
    x0=[1000,2,5]
    s=minimize(objective,x0,dffSi,method='SLSQP')
    l.append(s)
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfL_Si={'Energy':[12,18,24,30],'Thc':thn,'beta':bn,'n':nn}

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs

[1.23877521e+03 1.31544820e+00 5.14190264e-02]
[4.91092260e+04 4.42131258e+00 1.67389452e+01]
[3.49457921e+03 1.44229922e+00 4.69958391e+00]
[5.12484186e+03 1.65221564e+00 5.30533038e+00]


In [265]:
mequation(0,1.15173925e+06,7.93504140,3.22197009e+01)

1151739.25

In [266]:
dicfL_Si

{'Energy': [12, 18, 24, 30],
 'Thc': [1238.7752138131912,
  49109.225958286755,
  3494.5792084849395,
  5124.841862480529],
 'beta': [1.3154482031995838,
  4.421312577470428,
  1.4422992174615823,
  1.6522156374818326],
 'n': [0.05141902638755876,
  16.738945248671598,
  4.699583912041353,
  5.305330381324715]}

In [267]:
l=[]
for e0 in [12,18,24,30]:
    x0=[1000,2,5]
    s=minimize(objective,x0,dffGlass,method='SLSQP')
    l.append(s)
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfL_Glass={'Energy':[12,18,24,30],'Thc':thn,'beta':bn,'n':nn}

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:726: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs

[8.01865114e+03 3.46301734e+00 9.51833812e+00]
[1.07428284e+04 3.32936800e+00 9.36202786e+00]
[  0.85428213  -6.37532078 -27.74084694]
[  1.55447327  -5.88468701 -24.66386503]


In [279]:
l=[]
for e0 in [12,18,24,30]:
    x0=[1000,2,5]
    s=minimize(objective,x0,dffSS)
    l.append(s)
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfL_SS={'Energy':[12,18,24,30],'Thc':thn,'beta':bn,'n':nn}

[9.95420213e+05 1.02201756e+01 1.29095516e+01]
[5.37869898e+05 7.41067287e+00 1.95672472e+01]
[6.02082085e+03 2.47298455e+00 4.89820649e+00]
[4.62604791e+03 1.81033925e+00 3.38425138e+00]


Dejando Fijo el espesor crítico

In [269]:
#Stainless Steel 
SS={12:591.44,18:1699.65,24:3115.59,30:4783.12}
SS.values
#silicon
Si={12:936.51,18:1961.81,24:3227.94,30:4566.89}
#glass
Glass={12:934.41,18:1984.22,24:3170.76,30:4598.13}

In [270]:
def mequation2(I,Thc,beta,n):
    """
    Analithic Function to relate the thickness of a film with its relative ratio of intensities, i.e I_r
    """
    Thc=Si[e0]
    return Thc*np.exp(-beta*I**(1.0/n))
def objective2(x,df2):
    """
    El valor que retorne la función es el que se busca minimizar
    """
    thc=Si[e0]
    b=x[1]
    n=x[2]
    #print(e0)
    df2['Equation'] = mequation2(df2.I_ratio,thc,b,n)
    df2['Discrepancy'] = (df2.index.get_level_values('Thickness')-df2.Equation)/df2.index.get_level_values('Thickness')*100
    dfaux=df2[df2.I_ratio!=0]
    return dfaux.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()#df2.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()

In [271]:
l,thcc=[],[]
for e0 in [12,18,24,30]:
    x0=[Si[e0],2,5]
    s=minimize(objective2,x0,dffSi,method='Powell')
    l.append(s)
    thcc.append(Si[e0])
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfFix_Si={'Energy':[12,18,24,30],'Thc':thcc,'beta':bn,'n':nn}

[9.44449021e+02 7.97800553e-01 4.57158758e-01]
[1.96997749e+03 1.04557138e+00 2.82498458e+00]
[3.23660030e+03 1.35157175e+00 4.36658770e+00]
[4.57534059e+03 1.51947397e+00 4.83100218e+00]


In [272]:
def mequation2(I,Thc,beta,n):
    """
    Analithic Function to relate the thickness of a film with its relative ratio of intensities, i.e I_r
    """
    Thc=Glass[e0]
    return Thc*np.exp(-beta*I**(1.0/n))
def objective2(x,df2):
    """
    El valor que retorne la función es el que se busca minimizar
    """
    thc=Glass[e0]
    b=x[1]
    n=x[2]
    #print(e0)
    df2['Equation'] = mequation2(df2.I_ratio,thc,b,n)
    df2['Discrepancy'] = (df2.index.get_level_values('Thickness')-df2.Equation)/df2.index.get_level_values('Thickness')*100
    dfaux=df2[df2.I_ratio!=0]
    return dfaux.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()#df2.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()

In [273]:
l,thcc=[],[]
for e0 in [12,18,24,30]:
    x0=[Glass[e0],2,5]
    s=minimize(objective2,x0,dffGlass,method='Powell')
    l.append(s)
    thcc.append(Glass[e0])
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfFix_Glass={'Energy':[12,18,24,30],'Thc':thcc,'beta':bn,'n':nn} 

[1.68992506e+03 8.31798906e+00 6.75938725e-01]
[1.99581869e+03 1.79680575e+00 2.51537975e+00]
[3.17904099e+03 1.94309059e+00 3.28866488e+00]
[4.60879714e+03 2.14659769e+00 4.02836538e+00]


In [282]:
def mequation2(I,Thc,beta,n):
    """
    Analithic Function to relate the thickness of a film with its relative ratio of intensities, i.e I_r
    """
    Thc=SS[e0]
    return Thc*np.exp(-beta*I**(1.0/n))
def objective2(x,df2):
    """
    El valor que retorne la función es el que se busca minimizar
    """
    thc=SS[e0]
    b=x[1]
    n=x[2]
    #print(e0)
    df2['Equation'] = mequation2(df2.I_ratio,thc,b,n)
    df2['Discrepancy'] = (df2.index.get_level_values('Thickness')-df2.Equation)/df2.index.get_level_values('Thickness')*100
    dfaux=df2[df2.I_ratio!=0]
    return dfaux.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()#df2.loc[(e0,20):(e0,5000)].Discrepancy.pow(2).sum()

In [284]:
l,thcc=[],[]
for e0 in [12,18,24,30]:
    x0=[SS[e0],2,5]
    s=minimize(objective2,x0,dffSS,method='Powell')
    l.append(s)
    thcc.append(SS[e0])
thn,bn,nn = [], [], []
for i in l:
    print(i.x)
    thn.append(i.x[0])
    bn.append(i.x[1])
    nn.append(i.x[2])
dicfFix_SS={'Energy':[12,18,24,30],'Thc':thcc,'beta':bn,'n':nn}

[9.92521201e+03 1.69932591e+02 5.37494736e-01]
[1725.75121483    2.18733562    1.78692661]
[3.12369266e+03 1.81972469e+00 2.75913510e+00]
[4.79088379e+03 1.84727920e+00 3.48214439e+00]


In [276]:
path1='C:\\Users\\Juan Pablo Nicolás\\Documents\\FISICA\\FISICA ESTUDIO\\MICROSCOPIA ELECTRONICA\\paper ecuacion Ene2021\\Sim_batch\\Matrix Simulation'

In [277]:
pd.DataFrame(dicfL_Si).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='Si_')
pd.DataFrame(dicfL_Glass).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='Glass_')
pd.DataFrame(dicfL_SS).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='SS_to_excel')
pd.DataFrame(dicfFix_Si).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='Si_Thcfix')
pd.DataFrame(dicfFix_Glass).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='Glass_Thcfix')
pd.DataFrame(dicfFix_SS).to_excel(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx',sheet_name='SS_Thcfix')

In [278]:
with pd.ExcelWriter(path1+'\\'+'Ajuste_exp_Si_Glass_SS.xlsx') as writer:  
    pd.DataFrame(dicfL_Si).to_excel(writer,sheet_name='Si_')
    pd.DataFrame(dicfL_Glass).to_excel(writer,sheet_name='Glass_')
    pd.DataFrame(dicfL_SS).to_excel(writer,sheet_name='SS_to_excel')
    pd.DataFrame(dicfFix_Si).to_excel(writer,sheet_name='Si_Thcfix')
    pd.DataFrame(dicfFix_Glass).to_excel(writer,sheet_name='Glass_Thcfix')
    pd.DataFrame(dicfFix_SS).to_excel(writer,sheet_name='SS_Thcfix')

In [232]:
dffSi

I_ratio     Equation  Discrepancy
Energy Thickness                                    
12.0   430        0.988868  1002.879458  -133.227781
       1030       0.008367  2596.911852  -152.127364
       2140       0.003030  2890.305679   -35.061013
       3060       0.000000  4566.890000   -49.244771
18.0   430        3.063326   672.405280   -56.373321
       1030       0.124709  1701.157303   -65.160903
       2140       0.001997  3001.744263   -40.268423
       3060       0.000653  3273.578425    -6.979687
24.0   430        5.782476   513.682128   -19.460960
       1030       0.458273  1253.557504   -21.704612
       2140       0.006284  2682.639599   -25.356991
       3060       0.000000  4566.890000   -49.244771
30.0   430        8.576979   426.586030     0.793947
       1030       0.862567  1046.189318    -1.571778
       2140       0.033328  2154.042419    -0.656188
       3060       0.002109  2987.497523     2.369362